// <auto-generated />
using System;
using BakerAddressBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

/// <summary>
/// Baker Address Book - Model Snapshot
/// Author: Jacob Baker
/// Created: 2025-09-21
/// Description:
/// Represents a snapshot of the current EF Core model for the Baker Address Book application.
/// Used by EF Core Migrations to track changes to the model and database schema.
/// Auto-generated by EF Core; contains entity configurations and seed data.
/// </summary>
namespace BakerAddressBook.Migrations
{
    /// <summary>
    /// Snapshot of the EF Core model for BakerAppDbContext.
    /// This class is used internally by EF Core Migrations to determine schema differences.
    /// </summary>
    [DbContext(typeof(BakerAppDbContext))]
    partial class BakerAppDbContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// Builds the EF Core model for this snapshot.
        /// </summary>
        /// <param name="modelBuilder">Builder used to configure entities, properties, relationships, and seed data.</param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakerAddressBook.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Friend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("BakerAddressBook.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryId = 2,
                            DateCreated = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            LastName = "Kelly",
                            Nickname = "Ally",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            LastName = "Baker",
                            PhoneNumber = "770-423-6789 "
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charlie",
                            LastName = "Baker",
                            Nickname = "Chuck",
                            PhoneNumber = "476-543-2211"
                        });
                });

            modelBuilder.Entity("BakerAddressBook.Models.Contact", b =>
                {
                    b.HasOne("BakerAddressBook.Models.Category", "Category")
                        .WithMany("Contacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BakerAddressBook.Models.Category", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
